// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDusUqgRAi-RX2OEqDNtS4nKOKDlAGBq8',
    appId: '1:16032415528:web:aabe43e290a8e351161a1d',
    messagingSenderId: '16032415528',
    projectId: 'kungadi-53b2a',
    authDomain: 'kungadi-53b2a.firebaseapp.com',
    databaseURL: 'https://kungadi-53b2a-default-rtdb.firebaseio.com',
    storageBucket: 'kungadi-53b2a.firebasestorage.app',
    measurementId: 'G-PL40K0VVMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB65mFz5VTJfPAtaSPM5ze25d5lod4xKjw',
    appId: '1:16032415528:android:7fbf858eae37d9bd161a1d',
    messagingSenderId: '16032415528',
    projectId: 'kungadi-53b2a',
    databaseURL: 'https://kungadi-53b2a-default-rtdb.firebaseio.com',
    storageBucket: 'kungadi-53b2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPmcN__FtU9ju6edQmGEtEo7sc4xITyCM',
    appId: '1:16032415528:ios:85dc96277d64c3dd161a1d',
    messagingSenderId: '16032415528',
    projectId: 'kungadi-53b2a',
    databaseURL: 'https://kungadi-53b2a-default-rtdb.firebaseio.com',
    storageBucket: 'kungadi-53b2a.firebasestorage.app',
    iosBundleId: 'com.example.kunGadi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPmcN__FtU9ju6edQmGEtEo7sc4xITyCM',
    appId: '1:16032415528:ios:85dc96277d64c3dd161a1d',
    messagingSenderId: '16032415528',
    projectId: 'kungadi-53b2a',
    databaseURL: 'https://kungadi-53b2a-default-rtdb.firebaseio.com',
    storageBucket: 'kungadi-53b2a.firebasestorage.app',
    iosBundleId: 'com.example.kunGadi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDusUqgRAi-RX2OEqDNtS4nKOKDlAGBq8',
    appId: '1:16032415528:web:4bac1bdcb7426e4a161a1d',
    messagingSenderId: '16032415528',
    projectId: 'kungadi-53b2a',
    authDomain: 'kungadi-53b2a.firebaseapp.com',
    databaseURL: 'https://kungadi-53b2a-default-rtdb.firebaseio.com',
    storageBucket: 'kungadi-53b2a.firebasestorage.app',
    measurementId: 'G-NWXK2F9D6J',
  );

}